disabled_rules:
  - identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example/Pods/BrightFutures/*
  - Example/Pods/Result/*
  - Tests

included:
  - Source
  - Example

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  warning: 130

file_length:
  warning: 390
  error: 400
