disabled_rules:
  - identifier_name

included:
  - Source
  - Example

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Example/Pods
  - Tests

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  warning: 130

file_length:
  warning: 390
  error: 400
